<def f='include/c++/5/exception' l='63' type='void std::exception::exception()'/>
