<dec f='include/python3.5m/pyerrors.h' l='236' type='PyObject * PyErr_SetFromErrnoWithFilename(PyObject * exc, const char * filename)'/>
