<dec f='include/python3.5m/pyerrors.h' l='284' type='PyObject * PyErr_SetExcWithArgsKwargs(PyObject * , PyObject * , PyObject * )'/>
