<def f='tensorflow/tensorflow/core/lib/core/errors.h' l='111' macro='1' type='bool tensorflow::errors::IsInternal(const ::tensorflow::Status &amp; status)'/>
<use f='tensorflow/tensorflow/core/common_runtime/direct_session.cc' l='664' u='c' c='_ZN10tensorflow13DirectSession3RunERKNS_10RunOptionsERKSt6vectorISt4pairISsNS_6TensorEESaIS7_EERKS4_ISsSaISsEESF_PS4_IS6_SaIS6_EEPNS_11RunMetadataE'/>
<use f='tensorflow/tensorflow/core/common_runtime/direct_session.cc' l='683' u='c' c='_ZN10tensorflow13DirectSession3RunERKNS_10RunOptionsERKSt6vectorISt4pairISsNS_6TensorEESaIS7_EERKS4_ISsSaISsEESF_PS4_IS6_SaIS6_EEPNS_11RunMetadataE'/>
