<dec f='include/python3.5m/pyerrors.h' l='318' type='PyObject * _PyErr_TrySetFromCause(const char * prefix_format)'/>
<doc f='include/python3.5m/pyerrors.h' l='305'>/* Helper that attempts to replace the current exception with one of the
 * same type but with a prefix added to the exception text. The resulting
 * exception description looks like:
 *
 *     prefix (exc_type: original_exc_str)
 *
 * Only some exceptions can be safely replaced. If the function determines
 * it isn&apos;t safe to perform the replacement, it will leave the original
 * unmodified exception in place.
 *
 * Returns a borrowed reference to the new exception (if any), NULL if the
 * existing exception was left in place.
 */</doc>
