<dec f='include/python3.5m/pyerrors.h' l='232' type='PyObject * PyErr_SetFromErrnoWithFilenameObject(PyObject * , PyObject * )'/>
